spring:
  jpa:
    show-sql: false
    database-platform: com.mrray.datadesensitiveserver.config.SQLiteDialect
    generate-ddl: true
  application:
    name: data-desensitive-server

sqlite:
  dbName: a.db

server:
  port: 8080

constant:
  rows: 10000 #每次脱敏处理行数
  samples: 1000 #样本行数

daas-uri: daas-meta0.tpaas.youedata.com