INSERT INTO `t_algorithm` VALUES ('3', 'c7mnxxai', 'BankcardAlgorithm', '提供银行卡号类敏感信息发现以及个人账号标识掩码等处理方式', '银行卡', '', '3');
INSERT INTO `t_algorithm` VALUES ('4', 'omxsmx3v', 'CellphoneAlgorithm', '提供手机号类敏感信息发现以及中间四位掩码等处理方式', '手机号', '', '4');
INSERT INTO `t_algorithm` VALUES ('5', '13ajsety', 'DateAlgorithm', '提供时间类敏感信息发现以及统一时间等处理方式', '时间', '', '6');
INSERT INTO `t_algorithm` VALUES ('6', 'clnmpzch', 'IDAlgorithm', '提供身份证号类敏感信息发现以及保留地址识别码等处理方式', '身份证', '', '1');
INSERT INTO `t_algorithm` VALUES ('7', 'amhswml1', 'NameAlgorithm', '提供中文姓名类敏感信息发现以及保留姓氏及格式等处理方式', '姓名', '', '5');
INSERT INTO `t_algorithm` VALUES ('8', 'cuygfzvt', 'TelephoneAlgorithm', '提供座机类敏感信息发现以及保留区号等处理方式', '固定电话', '', '7');
INSERT INTO `t_algorithm` VALUES ('9', '367i4pb5', 'AddressAlgorithm', '提供中文地址类敏感信息发现以及保留省市其余掩码等处理方式', '地址', '', '8');
INSERT INTO `t_algorithm` VALUES ('10', 'wd5blopo', 'SocialCreditAlgorithm', '提供信用代码类敏感信息发现以及组织机构代码掩码等处理方式', '信用代码', '', '2');
INSERT INTO `t_algorithm` VALUES ('11', 'dsawqu34', 'EmailAlgorithm', '提供邮箱地址类敏感信息发现以及@前掩码等处理方式', '邮箱地址', '', '9');
INSERT INTO `t_algorithm` VALUES ('12', 'vjd47ewr', 'NumberAlgorithm', '提供通用数值类敏感信息发现及固定数值替换等处理方式', '通用数值', '\0', '10');
INSERT INTO `t_algorithm` VALUES ('13', 'tt125ert', 'StringAlgorithm', '提供通用字符串类敏感信息发现及保留前X个字符等处理方式', '通用字符串', '\0', '11');
INSERT INTO `t_mode` VALUES ('1', 'ywya6n8o', '保留地址识别码', 'IDone', '6');
INSERT INTO `t_mode` VALUES ('2', '4m26wwjr', '保留出生日期识别码', 'IDtwo', '6');
INSERT INTO `t_mode` VALUES ('3', 'rpchl7ym', '保留地址及出生日期识别码', 'IDthree', '6');
INSERT INTO `t_mode` VALUES ('4', 'yxtcrufg', '全部随机数', 'IDfour', '6');
INSERT INTO `t_mode` VALUES ('5', 'n9g8fcjr', '不脱敏', '', '6');
INSERT INTO `t_mode` VALUES ('6', 'wabbp61f', '个人账号标识掩码', 'bankcardone', '3');
INSERT INTO `t_mode` VALUES ('7', 'rwsq55rb', '全部随机数', 'bankcardtwo', '3');
INSERT INTO `t_mode` VALUES ('8', '2nhnb0xw', '不脱敏', '', '3');
INSERT INTO `t_mode` VALUES ('9', '30ku3vgx', '中间四位掩码', 'cellphoneone', '4');
INSERT INTO `t_mode` VALUES ('10', 'yk1uqush', '最后四位掩码', 'cellphonetwo', '4');
INSERT INTO `t_mode` VALUES ('11', 'btohhr8u', '后八位随机数', 'cellphonethree', '4');
INSERT INTO `t_mode` VALUES ('12', 'zrgwgxuf', '不脱敏', '', '4');
INSERT INTO `t_mode` VALUES ('13', 'uot5qukm', '保留姓氏及姓名字数', 'nameone', '7');
INSERT INTO `t_mode` VALUES ('14', 'q54szj3p', '保留姓氏但不保留字数', 'nametwo', '7');
INSERT INTO `t_mode` VALUES ('15', '1nfncoa7', '不脱敏', '', '7');
-- INSERT INTO `t_mode` VALUES ('16', '09xoibiv', '替换为统一时间', 'dateone', '5');
INSERT INTO `t_mode` VALUES ('17', 'n0alqkes', '手动设置时间', 'datetwo', '5');
INSERT INTO `t_mode` VALUES ('18', 'wvo013tm', '不脱敏', '', '5');
INSERT INTO `t_mode` VALUES ('19', 'ugge3eyf', '保留区号', 'telephoneone', '8');
INSERT INTO `t_mode` VALUES ('20', 'vd2ci7y9', '保留区县号', 'telephonetwo', '8');
INSERT INTO `t_mode` VALUES ('21', 'mtxm98xc', '全部随机数', 'telephonethree', '8');
INSERT INTO `t_mode` VALUES ('22', 'zcybbpkt', '不脱敏', '', '8');
INSERT INTO `t_mode` VALUES ('23', 'pdbqpsuk', '保留省市', 'addressone', '9');
INSERT INTO `t_mode` VALUES ('24', '03zgh1d7', '保留省市区', 'addresstwo', '9');
INSERT INTO `t_mode` VALUES ('25', '5rcfuagw', '不脱敏', '', '9');
INSERT INTO `t_mode` VALUES ('26', 'h4j1nd6v', '组织机构代码掩码', 'socialCreditone', '10');
INSERT INTO `t_mode` VALUES ('27', 'ajc29g2q', '税务登记证号码掩码', 'socialCredittwo', '10');
INSERT INTO `t_mode` VALUES ('28', '7lurgzya', '不脱敏', '', '10');
INSERT INTO `t_mode` VALUES ('29', 'g5rty6fe', '@前字符掩码', 'emailone', '11');
INSERT INTO `t_mode` VALUES ('30', 'vv3xy5fg', '不脱敏', '', '11');
INSERT INTO `t_mode` VALUES ('31', 'r2t5weew', '固定数值替换', 'numberone', '12');
INSERT INTO `t_mode` VALUES ('32', 'bvn8ter6', '向上或向下范围取值', 'numbertwo', '12');
INSERT INTO `t_mode` VALUES ('33', 'ytedfdsw', '范围随机数替换', 'numberthree', '12');
INSERT INTO `t_mode` VALUES ('34', 'dt5iohg8', '不脱敏', '', '12');
INSERT INTO `t_mode` VALUES ('35', 'asewreyr', '保留前X个字符', 'stringone', '13');
INSERT INTO `t_mode` VALUES ('36', 'euldu932', '保留后X个字符', 'stringtwo', '13');
INSERT INTO `t_mode` VALUES ('37', 'iowj83ks', '掩码前X个字符', 'stringthree', '13');
INSERT INTO `t_mode` VALUES ('38', 'wfubvw4v', '掩码后X个字符', 'stringfour', '13');
INSERT INTO `t_mode` VALUES ('39', '34ndt5if', '返回前X个字符', 'stringfive', '13');
INSERT INTO `t_mode` VALUES ('40', '0sdiw84b', '返回后X个字符', 'stringsix', '13');
INSERT INTO `t_mode` VALUES ('41', '93mbuel4', '不脱敏', '', '13');